/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.reinaldo.utilidadesv2.view;

import br.com.reinaldo.utilidadesv2.constantes.VariaveisComuns;
import br.com.reinaldo.utilidadesv2.entidades.MaquinaEntity;
import br.com.reinaldo.utilidadesv2.regras.CryptoPass;
import br.com.reinaldo.utilidadesv2.utils.AcoesComuns;
import br.com.reinaldo.utilidadesv2.utils.CryptoUtil;
import javax.swing.JOptionPane;

/**
 *
 * @author desenv
 */
public class AdicionarEditarCrypto extends javax.swing.JFrame {
    
    public static final int VER = 0;
    public static final int ADICIONAR = 1;
    public static final int EDITAR = 2;
    
    private MaquinaEntity maquinaOriginal;
    private int acao;
    private FramePrincipal paraRecarregar;

    /**
     * Creates new form AdicionarEditarCrypto
     */
    public AdicionarEditarCrypto() {
        initComponents();
        setDefaultCloseOperation(HIDE_ON_CLOSE);
    }
    
    public void preparar(int funcao, MaquinaEntity maquina, FramePrincipal pParaRecarregar) {
        maquinaOriginal = maquina;
        acao = funcao;
        paraRecarregar = pParaRecarregar;
        
        addMaquinaTxtLabel.setText("");
        addMaquinaTxtLabel.setEditable(false);
        
        addMaquinaTxtGrupo.setText("");
        addMaquinaTxtNome.setText("");
        addMaquinaTxtUsuario.setText("");
        addMaquinaTxtSenha.setText("");
        addMaquinaTxtDescricao.setText("");
        addMaquinaTxtURL.setText("");
        addMaquinaTxtComandoPersonalizado.setText("");
        addMaquinaRadioPutty.setSelected(true);
        
        if (funcao == VER || funcao == EDITAR) {
            try {
                addMaquinaTxtGrupo.setText(maquina.getGrupo());
                addMaquinaTxtNome.setText(maquina.getNome());
                addMaquinaTxtUsuario.setText(maquina.getUsuario());
                addMaquinaTxtSenha.setText(maquina.getSenhaAberta());
                addMaquinaTxtDescricao.setText(maquina.getDescricao());
                addMaquinaTxtURL.setText(maquina.getUrl());
                addMaquinaTxtComandoPersonalizado.setText(maquina.getComandoPersonalizado());
                
                if (maquina.getTipoTerminal() == MaquinaEntity.TIPO_TERMINAL_NAVEGADOR) {
                    addMaquinaRadioNavegador.setSelected(true);
                } else if (maquina.getTipoTerminal() == MaquinaEntity.TIPO_TERMINAL_SHELL) {
                    addMaquinaShell.setSelected(true);
                } else if (maquina.getTipoTerminal() == MaquinaEntity.TIPO_TERMINAL_PERSONALIZADO) {
                    addMaquinaPersonalizado.setSelected(true);
                } else {
                    addMaquinaRadioPutty.setSelected(true);
                }
                
            } catch (Exception ex) {}
        }
        if (funcao == VER) {
            addMaquinaTxtGrupo.setEditable(false);
            addMaquinaTxtNome.setEditable(false);
            addMaquinaTxtUsuario.setEditable(false);
            addMaquinaTxtSenha.setEditable(false);
            addMaquinaTxtDescricao.setEditable(false);
            addMaquinaBtnSalvar.setEnabled(false);
            addMaquinaRadioPutty.setEnabled(false);
            addMaquinaPersonalizado.setEnabled(false);
            addMaquinaShell.setEnabled(false);
            addMaquinaRadioNavegador.setEnabled(false);
            addMaquinaTxtComandoPersonalizado.setEditable(false);
            addMaquinaTxtURL.setEditable(false);
            try {
                addMaquinaTxtSenha.setText(maquina.getSenhaReduzida());
            } catch (Exception ex) {}
        } else {
            addMaquinaTxtGrupo.setEditable(true);
            addMaquinaTxtNome.setEditable(true);
            addMaquinaTxtUsuario.setEditable(true);
            addMaquinaTxtSenha.setEditable(true);
            addMaquinaTxtDescricao.setEditable(true);
            addMaquinaBtnSalvar.setEnabled(true);
            addMaquinaRadioPutty.setEnabled(true);
            addMaquinaPersonalizado.setEnabled(true);
            addMaquinaShell.setEnabled(true);
            addMaquinaRadioNavegador.setEnabled(true);
            addMaquinaTxtComandoPersonalizado.setEditable(true);
            addMaquinaTxtURL.setEditable(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        adicionarEditarRadioGrupoExecucao = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        addMaquinaTxtNome = new javax.swing.JTextField();
        addMaquinaTxtGrupo = new javax.swing.JTextField();
        addMaquinaTxtUsuario = new javax.swing.JTextField();
        addMaquinaTxtSenha = new javax.swing.JTextField();
        addMaquinaScrollDesc = new javax.swing.JScrollPane();
        addMaquinaTxtDescricao = new javax.swing.JTextArea();
        addMaquinaBtnSalvar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        addMaquinaTxtLabel = new javax.swing.JTextField();
        addMaquinaTxtURL = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        addMaquinaRadioNavegador = new javax.swing.JRadioButton();
        addMaquinaRadioPutty = new javax.swing.JRadioButton();
        addMaquinaShell = new javax.swing.JRadioButton();
        addMaquinaPersonalizado = new javax.swing.JRadioButton();
        addMaquinaTxtComandoPersonalizado = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Utilidades V2 - Detalhes");

        jLabel1.setText("Grupo:");

        jLabel2.setText("Endereço / Nome:");

        jLabel3.setText("Usuário:");

        jLabel4.setText("Senha:");

        jLabel5.setText("Descrição:");

        addMaquinaTxtDescricao.setColumns(20);
        addMaquinaTxtDescricao.setLineWrap(true);
        addMaquinaTxtDescricao.setRows(5);
        addMaquinaScrollDesc.setViewportView(addMaquinaTxtDescricao);

        addMaquinaBtnSalvar.setText("salvar");
        addMaquinaBtnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMaquinaBtnSalvarActionPerformed(evt);
            }
        });

        jLabel6.setText("Label / Apelido:");

        jLabel7.setText("URL:");

        jLabel8.setText("Execução: (botão abrir terminal)");

        adicionarEditarRadioGrupoExecucao.add(addMaquinaRadioNavegador);
        addMaquinaRadioNavegador.setText("Navegador");
        addMaquinaRadioNavegador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMaquinaRadioNavegadorActionPerformed(evt);
            }
        });

        adicionarEditarRadioGrupoExecucao.add(addMaquinaRadioPutty);
        addMaquinaRadioPutty.setText("Putty (windows)");
        addMaquinaRadioPutty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMaquinaRadioPuttyActionPerformed(evt);
            }
        });

        adicionarEditarRadioGrupoExecucao.add(addMaquinaShell);
        addMaquinaShell.setText("Shell (linux)");
        addMaquinaShell.setToolTipText("A senha será copiada para area de transferencia junto a abertura do terminal");
        addMaquinaShell.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMaquinaShellActionPerformed(evt);
            }
        });

        adicionarEditarRadioGrupoExecucao.add(addMaquinaPersonalizado);
        addMaquinaPersonalizado.setText("Personalizado");
        addMaquinaPersonalizado.setToolTipText("Caso nao exista a variavel %PWD% no comando, a senha sera copiada pela area de transferencia");
        addMaquinaPersonalizado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMaquinaPersonalizadoActionPerformed(evt);
            }
        });

        addMaquinaTxtComandoPersonalizado.setToolTipText("Exemplo: c:\\MobaXterm.exe -newtab \"ssh rs33196@spos7012\"");

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel9.setText("Utilize %SSN%, %USR% e %PWD% onde deseja que o programa insira o nome da máquina, usuário e senha");

        jLabel10.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel10.setText("Exemplo: cmd.exe /c start putty -load %SSN% -l %USR%  -pw %PWD%");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addMaquinaScrollDesc)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(addMaquinaBtnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addMaquinaTxtGrupo)
                            .addComponent(addMaquinaTxtNome)
                            .addComponent(addMaquinaTxtUsuario)
                            .addComponent(addMaquinaTxtSenha)
                            .addComponent(addMaquinaTxtLabel)
                            .addComponent(addMaquinaTxtURL)))
                    .addComponent(addMaquinaTxtComandoPersonalizado)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addMaquinaRadioPutty)
                            .addComponent(addMaquinaPersonalizado)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(addMaquinaRadioNavegador)
                            .addComponent(addMaquinaShell)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(addMaquinaTxtGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(addMaquinaTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3))
                            .addComponent(addMaquinaTxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4))
                    .addComponent(addMaquinaTxtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(addMaquinaTxtLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addMaquinaTxtURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addMaquinaScrollDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addMaquinaRadioNavegador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addMaquinaRadioPutty)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addMaquinaShell)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addMaquinaPersonalizado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addMaquinaTxtComandoPersonalizado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(addMaquinaBtnSalvar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addMaquinaBtnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMaquinaBtnSalvarActionPerformed
        
        if (addMaquinaTxtGrupo.getText() == null || "".equals(addMaquinaTxtGrupo.getText())) {
            mensagemErro("Informe o grupo dessa maquina");
            return;
        }
        
        if (addMaquinaTxtNome.getText() == null || "".equals(addMaquinaTxtNome.getText())) {
            mensagemErro("Informe o nome do servidor");
            return;
        }
        
        if (addMaquinaTxtSenha.getText() == null || "".equals(addMaquinaTxtSenha.getText())) {
            mensagemErro("Informe a senha de acesso ao servidor");
            return;
        }
        
        if (addMaquinaTxtUsuario.getText() == null || "".equals(addMaquinaTxtUsuario.getText())) {
            mensagemErro("Informe o usuario de acesso ao servidor");
            return;
        }
        
        if (addMaquinaPersonalizado.isSelected()) {
            if (addMaquinaTxtComandoPersonalizado.getText() == null || "".equals(addMaquinaTxtComandoPersonalizado.getText()) || "".equals(addMaquinaTxtComandoPersonalizado.getText().trim())) {
                mensagemErro("Informe o comando personalizado");
                return;
            }
        }
        
        final MaquinaEntity novaMaquina = new MaquinaEntity();
        novaMaquina.setDescricao(addMaquinaTxtDescricao.getText().trim());
        novaMaquina.setGrupo(addMaquinaTxtGrupo.getText().trim());
        novaMaquina.setLabel("asd");
        novaMaquina.setNome(addMaquinaTxtNome.getText().trim());
        try {
            novaMaquina.setSenha(CryptoUtil.getInstance().encrypt(VariaveisComuns.HASH, addMaquinaTxtSenha.getText().trim()));
        } catch (Exception ex) {}
        novaMaquina.setUsuario(addMaquinaTxtUsuario.getText().trim());
        novaMaquina.setUrl(addMaquinaTxtURL.getText().trim());
        novaMaquina.setComandoPersonalizado(addMaquinaTxtComandoPersonalizado.getText().trim());
        
        if (addMaquinaRadioNavegador.isSelected()) novaMaquina.setTipoTerminal(MaquinaEntity.TIPO_TERMINAL_NAVEGADOR);
        if (addMaquinaRadioPutty.isSelected()) novaMaquina.setTipoTerminal(MaquinaEntity.TIPO_TERMINAL_PUTTY);
        if (addMaquinaShell.isSelected()) novaMaquina.setTipoTerminal(MaquinaEntity.TIPO_TERMINAL_SHELL);
        if (addMaquinaPersonalizado.isSelected()) novaMaquina.setTipoTerminal(MaquinaEntity.TIPO_TERMINAL_PERSONALIZADO);
        
        if (acao == EDITAR) {
            editarMaquina(novaMaquina);
        } else if (acao == ADICIONAR) {
            adicionarMaquina(novaMaquina);
        } 
        
        AcoesComuns.procurarProperties();
        paraRecarregar.recarregarArvore();
        setVisible(false);
    }//GEN-LAST:event_addMaquinaBtnSalvarActionPerformed

    private void addMaquinaRadioPuttyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMaquinaRadioPuttyActionPerformed
        addMaquinaTxtComandoPersonalizado.setEnabled(false);
    }//GEN-LAST:event_addMaquinaRadioPuttyActionPerformed

    private void addMaquinaPersonalizadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMaquinaPersonalizadoActionPerformed
        addMaquinaTxtComandoPersonalizado.setEnabled(true);
    }//GEN-LAST:event_addMaquinaPersonalizadoActionPerformed

    private void addMaquinaShellActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMaquinaShellActionPerformed
        addMaquinaTxtComandoPersonalizado.setEnabled(false);
    }//GEN-LAST:event_addMaquinaShellActionPerformed

    private void addMaquinaRadioNavegadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMaquinaRadioNavegadorActionPerformed
        addMaquinaTxtComandoPersonalizado.setEnabled(false);
    }//GEN-LAST:event_addMaquinaRadioNavegadorActionPerformed

    
    private void editarMaquina(final MaquinaEntity novaMaquina) {
        final int op = JOptionPane.showConfirmDialog(getContentPane(), "Tem certeza que deseja os dados do servidor \"" + maquinaOriginal.getNome() + "\"?");
        if (op == JOptionPane.OK_OPTION) {
            try {
                CryptoPass.alterarMaquinaNoProperties(maquinaOriginal, novaMaquina);
            } catch (Exception ex) {}
        }
    }
    
    private void adicionarMaquina(final MaquinaEntity novaMaquina) {
        AcoesComuns.adicionarNoProperties(novaMaquina.toString());
    }
    
    
    private void mensagemErro(final String texto) {
        JOptionPane.showMessageDialog(getContentPane(), texto, "Erro", JOptionPane.ERROR_MESSAGE);
    }

    private void mensagemAviso(final String texto) {
        JOptionPane.showMessageDialog(getContentPane(), texto, "Atencao", JOptionPane.WARNING_MESSAGE);
    }

    private void mensagemInformacao(final String texto) {
        JOptionPane.showMessageDialog(getContentPane(), texto, "Atencao", JOptionPane.INFORMATION_MESSAGE);
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton addMaquinaBtnSalvar;
    public javax.swing.JRadioButton addMaquinaPersonalizado;
    public javax.swing.JRadioButton addMaquinaRadioNavegador;
    public javax.swing.JRadioButton addMaquinaRadioPutty;
    public javax.swing.JScrollPane addMaquinaScrollDesc;
    public javax.swing.JRadioButton addMaquinaShell;
    public javax.swing.JTextField addMaquinaTxtComandoPersonalizado;
    public javax.swing.JTextArea addMaquinaTxtDescricao;
    public javax.swing.JTextField addMaquinaTxtGrupo;
    public javax.swing.JTextField addMaquinaTxtLabel;
    public javax.swing.JTextField addMaquinaTxtNome;
    public javax.swing.JTextField addMaquinaTxtSenha;
    public javax.swing.JTextField addMaquinaTxtURL;
    public javax.swing.JTextField addMaquinaTxtUsuario;
    public javax.swing.ButtonGroup adicionarEditarRadioGrupoExecucao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
